### ISSUE TITLE
Modal background not disappears

### ISSUE THREAD

**Issue by zone1980** [eissasoubhi/summernote-gallery#2]
After closing the image gallery modal, the graybackground under the modal not disappears.

**Comment by eissasoubhi** [comment]
it's fixed https://github.com/eissasoubhi/summernote-gallery/commit/d7f70e57a33d363d1badf567cd688fcf90c4aa25

You can use https://github.com/eissasoubhi/summernote-bricks which has more features and a better support.
Thanks.
