### ISSUE TITLE
two summernotes on one page sets images on the last  textfield

### ISSUE THREAD

**Issue by mlyght** [eissasoubhi/summernote-gallery#5]
Hi. First of all Great job on building the plugin.
I have a problem attaching images on 2 summernotes in the same page.  on clicking "ok" button. it send on the last summernote on the the page. However  the images are not displayed whenever i click the extensions icon. I have to reload the whole page. Kindly help Thanks.

**Comment by eissasoubhi** [comment]
Hi @mlyght, 

Indeed, if there is more than one summenote instance on the same page, the images will always be inserted in the last summernote instance editor, it's fixed now https://github.com/eissasoubhi/summernote-gallery/commit/a67875894093d3be145e8404b31cb7ab080a843f.
Regarding the other issue:

> However the images are not displayed whenever i click the extensions icon 

I couldn't reproduce it, can you provide me with more details, do you see any error on the console?

**Comment by mlyght** [comment]
The update works good. thanks man. 

About the second issue.
when you click the gallery button the first time on summernote the modal loads images like on the image below

![Capture1](https://user-images.githubusercontent.com/6526493/86950916-7d7fd080-c159-11ea-848f-b94734564214.JPG)

However when you click the gallery button on summernote after that the modal does not display any image and there is no error displaying on the console.

![Capture](https://user-images.githubusercontent.com/6526493/86950924-7f499400-c159-11ea-9162-1a1dc45300c0.JPG)

thanks very much.

**Comment by eissasoubhi** [comment]
So to produce the problem:
1. You click the gallery button to open the modal
2. You select some images and click the "Ok" button
3. You click the gallery button for the second time
4. The modal opens, but this time with no image 

Is that right?

Can you show me the options you passed to the gallery?

Thank you.

**Comment by mlyght** [comment]
Thats correct.



This is my summernote function

 `$(function () {
        
                $('#specification').summernote({
                    placeholder: 'Add Item Specification',
                    tabsize: 2,
                    height: 100,
                    toolbar: [
                              ['style', ['style']],
                              ['font', ['bold', 'underline', 'clear']],
                              ['color', ['color']],
                              ['para', ['ul', 'ol', 'paragraph']],
                              ['table', ['table']],
                              ['insert', ['link', 'picture', 'video']],
                              ['extensions', ['gallery']],
                              ['view', ['fullscreen', 'codeview', 'help']]
                        ],
                    gallery: {
                                source: {
                                    // data: data,
                                    url: '/images',
                                    responseDataKey: 'files',
                                    nextPageKey: 'links.next',
                                },
                                modal: {
                                    loadOnScroll: true,
                                    maxHeight: 600,
                                    title: "Images",
                                    close_text: 'Close',
                                    ok_text: 'OK',
                                    selectAll_text: 'Select All',
                                    deselectAll_text: 'Diselect All',
                                    noImageSelected_msg: 'No image was selected, please select one by clicking it!',
                                }
                    }
                })
        })`

**Comment by eissasoubhi** [comment]
I added the fix https://github.com/eissasoubhi/summernote-gallery/commit/0791fbb74a9a1ede4124537cbc7bdfe97ec82e60, can you please confirm that the problem is fixed?

**Comment by mlyght** [comment]
Working fine now thanks  @eissasoubhi this is a great plugin. 5 star plugin.
