### ISSUE TITLE
not trigger another ajax request after load the first time

### ISSUE THREAD

**Issue by ryumada** [eissasoubhi/summernote-gallery#7]
> This feature has been added in the new version [3586ff0](https://github.com/eissasoubhi/summernote-gallery/commit/3586ff0d9e0344496b521149b433dfe37ef1b6ea).
> see the demo http://eissasoubhi.github.io/summernote-gallery/
> 
> Thanks for the suggestion.

Hi, I have an Issue with this feature, the modal won't load another ajax request, I have followed all your instruction but still not working on my project. ~I have looked at your demo too, but I think it doesn't explain how to use this.~. EDIT: I have changed the .json to .php url on the demo and placed it on apache server, running it on my localhost page, but still not working.

My server is working just fine, It get the json data with `links.next` url on response and of course it has `?page=2`. If I visit the link using `?page=2` it will get `?page=3` parameter and so on. the problem is the plugin won't trigger another ajax request.

here is my summernote-gallery settings,
```
gallery: { // summernote gallery settings
  source: {
    // data: [],
    url: url_getIndex + 
      "?page=" + url_getNextPage + 
      "&path=" + path +
      "&index=" + index +
      "&url_getIndex=" + url_getIndex +
      "&url_getNextPage=" + url_getNextPage +
      "&url_path=" + url_path +
      "&path=" + path,
    // responseDataKey: 'data',
    nextPageKey: 'links.next',
  },
  modal: {
    loadOnScroll: true,
    // maxHeight: 300,
    title: "Tambahkan Gambar",
    close_text: 'Batalkan',
    ok_text: 'Tambahkan',
    selectAll_text: 'Pilih Semua',
    deselectAll_text: 'Pilih Tidak Semua',
    noImageSelected_msg: 'Tidak ada gambar yang dipilih, harap pilih satu',
  }
}
```

and here is for the json file generated by my server,
[gallery.txt](https://github.com/eissasoubhi/summernote-gallery/files/5936755/gallery.txt)

What's the problem? Is there something I missed?

_Originally posted by @rizukiRyumada in https://github.com/eissasoubhi/summernote-gallery/issues/4#issuecomment-774461595_

**Comment by ryumada** [comment]
okay so, I got it fixed by adding more images to my json file, it makes the modal more longer so it trigger to show the scrollbar. Also in Bootstrap 4 there is a separated class that makes the modal scrollable inside the modal not scrollable on the browser, see:

[https://getbootstrap.com/docs/4.6/components/modal/#scrolling-long-content](https://getbootstrap.com/docs/4.6/components/modal/#scrolling-long-content)

On my project, I add `.modal-dialog-scrollable` to `.modal-dialog` and it works. This is happen because I'm using adminLTE 3 which uses Bootstrap 4 as the base version. 

But still the max height, the sum of json images data should makes a trigger to show the scrollbar in the modal. Or you can make the modal more shorter.

**Comment by eissasoubhi** [comment]
Fixed in https://github.com/eissasoubhi/summernote-gallery/commit/5ce29c18f0417b215221449b1df297aaf111bab0
